services:
  sample-db:
    image: postgres:15
    container_name: sample-db
    ports:
      - "5482:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sample_db
    volumes:
      - postgres-data:/var/lib/postgresql/data 
volumes:
  postgres-data: